Passman/Passman/urls.py
from django.urls import path, include, reverse
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.contrib.auth.decorators import login_required

admin.site.login = login_required(admin.site.login)

urlpatterns = [
    path('accounts/', include('apps.accounts.urls', namespace="accounts")),
    path('dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    path('encrypter/', include('apps.encrypter.urls', namespace="encrypter")),
    path("Ww33AVMWvekVt8UhxosX/YzWWxjPVfeI5j8UsJZzP/HL9eMqygOmEK1rQugoqY/2AaA8qIG35cA0dq0PisC/", admin.site.urls),
    path("", include('apps.portal.urls', namespace="portal")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

handler404 = 'apps.core.views.page_not_found'
handler500 = 'apps.core.views.server_error'
handler403 = 'apps.core.views.permission_denied'
handler400 = 'apps.core.views.bad_request'

Passman/apps/encrypter/urls.py
from . import views as v
from . import drfviews as dv
from rest_framework import routers
from django.contrib.auth.views import TemplateView
from django.urls import include, path

app_name = "encrypter"

router = routers.DefaultRouter()
router.register(r'passwords', dv.PasswordViewSet)
router.register(r'categories', dv.CategoryViewSet)
router.register(r'platforms', dv.PlatformViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path("", v.PassView, name="encrypter"),
    #path("locked", v.Locked, name="locked"),
    path("set", v.SetMaster, name="set"),
    path("get", v.GetMaster, name="get"),
    path("del", v.DelMaster, name="del"),
    path("store", v.StoreView, name="store"),
    path("cat_title", v.cat_save, name="categores"),
    path("title_form", v.title_form, name="title_form")
]

Passman/apps/encrypter/models.py
from django.db import models
from django.apps import apps
from django.conf import settings
# from accounts.models import User
# Create your models here.


class Categories(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    title = models.CharField(max_length=254)


class Passwords(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        Categories,
        on_delete=models.CASCADE
    )
    password = models.CharField(max_length=254, blank=True)
    platform = models.CharField(max_length=254)
    icon = models.CharField(max_length=254)


class Platform(models.Model):
    name = models.CharField(max_length=254, blank=True)
    icon = models.CharField(max_length=254, blank=True)
    background = models.CharField(max_length=254, blank=True)
    textColor = models.CharField(max_length=254, blank=True)

Passman/apps/encrypter/forms.py
from . models import Passwords, Categories
from django import forms
from django.forms import ModelForm, Form
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Row, Column, Field
from crispy_forms.bootstrap import PrependedText


class PassChoice(ModelForm):
    p = []
    mpassword = forms.CharField(max_length=254, widget=forms.PasswordInput())

    class Meta:
        model = Passwords
        fields = '__all__'
        widgets = {
            'password1': forms.PasswordInput(),
            'password2': forms.PasswordInput(),
            'password3': forms.PasswordInput(),
            'password4': forms.PasswordInput(),
            'password5': forms.PasswordInput(),
            'password6': forms.PasswordInput(),
            'password7': forms.PasswordInput(),
            'password8': forms.PasswordInput(),
            'password9': forms.PasswordInput(),
            'password10': forms.PasswordInput(),
        }

    def __init__(self, *args, **kwargs):
        super(PassChoice, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                Row(
                    Column(PrependedText('password1',
                                         '@', css_class='pwd-field')),
                    Column(PrependedText('password2',
                                         '@', css_class='pwd-field')),
                    Column(PrependedText('password3',
                                         '@', css_class='pwd-field')),
                    Column(PrependedText('password4',
                                         '@', css_class='pwd-field')),
                    Column(PrependedText('password5',
                                         '@', css_class='pwd-field')),
                    Column(PrependedText('password6',
                                         '@', css_class='pwd-field')),
                    Column(PrependedText('password7',
                                         '@', css_class='pwd-field')),
                    Column(PrependedText('password8',
                                         '@', css_class='pwd-field')),
                    Column(PrependedText('password9',
                                         '@', css_class='pwd-field')),
                    Column(PrependedText('password10',
                                         '@', css_class='pwd-field')),
                    Column(PrependedText('password11',
                                         '@', css_class='pwd-field'))
                )),

            # ButtonHolder(
            # Submit('submit', 'Submit', css_class='button white')
        )

    def clean(self):

        super(PassChoice, self).clean()
        for field in self.fields:
            self.p.append(self.cleaned_data.get(field))


class Titles(ModelForm):

    class Meta:
        model = Categories
        fields = '__all__'
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(Titles, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'Title',
                Row(
                    Column('title', css_class='pwd-field'))),)

    def clean(self):
        super(Titles, self).clean()


class Mpass(Form):
    mpassword = forms.CharField(max_length=254, widget=forms.PasswordInput())

    def clean(self):
        super(Mpass, self).clean()

Passman/apps/encrypter/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render, reverse
from django.utils import timezone
from . forms import PassChoice, Titles, Mpass
from . models import Categories, Passwords
from . utils import Encrypter
import json
# Create your views here.


def PassView(request):
    queryset = Categories.objects.filter(user=request.user)

    if request.method == 'POST' and request.is_ajax:
        pwd = request.POST.get('data')
        pobjs = json.loads(pwd)
        print(request.session['masterp'])
        for x in pobjs:
            x['value'] = Encrypter().encrypt(
                x['value'], request.session['masterp'])
            Passwords.objects.filter(id=x['id']).update(password=x['value'])
        return JsonResponse({'success': True})
    return render(request, "encrypter/categories.html")


def cat_save(request):
    print(request.body)


def title_form(request):
    if request.method == 'POST' and request.is_ajax:
        form = Titles(request.POST)
        if form.is_valid():
            titles = form.save(commit=False)
            titles.user = request.user
            form.save()
        return JsonResponse({'success': True})

    else:
        formtitle = Titles()
        return HttpResponse(formtitle)


def StoreView(request):
    catid = request.GET.get('cat')
    return render(request, "encrypter/store.html", {"catid": catid})


def SetMaster(request):
    if request.method == 'POST' and request.is_ajax:
        form = Mpass(request.POST)
        mp = request.POST.get('master-key')
        pwds = Passwords.objects.filter(user=request.user)
        if len(pwds) != 0:
            for x in pwds:
                password = x.password.strip('\"')
                if password != "":
                    print(password)
                    pwdnew = bytes.decode(Encrypter().decrypt(
                        password[2:-1], mp))
                    if pwdnew == "":
                        return JsonResponse({'success': False})
            request.session['masterp'] = request.POST.get('master-key')
            return JsonResponse({'success': True})

    else:
        form = Mpass()
        return HttpResponse(Mpass)


def GetMaster(request):
    if request.method == 'POST' and request.is_ajax:
        if request.session.has_key('masterp'):
            if request.POST.get('demand') == 'check':
                return JsonResponse({'master': request.session.has_key('masterp')})
            elif request.POST.get('demand') == 'grab':
                return JsonResponse({'master': request.session['masterp']})

    return JsonResponse({'master': 'notset'})


def DelMaster(request):
    if request.method == 'POST' and request.is_ajax:
        if request.session.has_key('masterp'):
            del request.session['masterp']
            return JsonResponse({'master': 'deleted'})

    return JsonResponse({'master': 'notset'})

Passman/apps/encrypter/templates/encrypter/_base.html
{% extends '_base.html' %}
{% block title %}{% endblock %}

{% block page %}
      <div class="page-main w-100 toggled">
        {% include 'dashboard/components/_sidebar.html' %}
        <div id="content">
            {% include "dashboard/components/_header.html" %}
          
            {% block content %}
            {% endblock %}
            
            {% include "dashboard/components/_footer.html" %}
        </div>        
      </div>
{% endblock %}

Passman/apps/encrypter/templates/encrypter/categories.html
{% extends 'encrypter/index.html' %}

{% block categories %}
{% csrf_token %}


<div id="master" class="master master-panel">
 <form id="mform" method="POST" action="{% url 'encrypter:set' %}" class="master-form">
 {% csrf_token %}
 <label for="master-key"><h3>Master Key</h3></label><br/>
 <input id="master-key" type="password" name="master-key" class="form-input">
 </form><br/>
 <input id="master-submit" type="submit"  value="Unlock" class="form-input master-form" />
</div>

<div id="panel" class="pass-panel">
<i class="cross-panel fa fa-2x fa-times" aria-hidden="true"></i>
  <div id="pass-row" class="row">
  </div>
</div>

<div id="cats">         
<div id="cats-inner" class="row">

</div>
 </div>
{% endblock %}

{% block footer_js %}

<script>
$(document).ready(function() {

var categs;
var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

/* Function to check if session cookies is set
------------------------------------------------*/

function checkcook()
{
$.ajax({
  url: "{% url 'encrypter:get' %}",
  type: "POST",
  headers: {"X-CSRFToken": csrftoken },
  data: {'demand':'check'},
  success: function(data){
    if(data.master == true)
    {
       $("#master").css("display","none");
       $("#cats").css("display","block");
       load_categories();
    }
    else{
      $("#master").css("display","block");
      $("#cats").css("display","none");
    }
  }
});
}
checkcook();

/* ADD CATEGORY FUNCTION 
---------------------------*/

$(document).on("click","#add_cat",function() {
  $(this).fadeTo(500, 0, "swing", function() {
    console.log("callback");
    var url = "{% url 'encrypter:title_form' %}";
    $.ajax({
      url: url,
      type: "GET",
      async: "false",
      crossOrigin: true,
      success: function(formtitle) {
        $("#cat_form").html(
          '<form id="title_form" action="' + url + '" method="POST">' +
            '{% csrf_token %}' +
            "<legend for='id_title' style='font-size:1.0em'>Name Your Collection</legend>" +
            formtitle +
            "</form>" + 
            "<button id='submit_form'>Submit</button>" 
        );
        $("#title_form").fadeTo(500, 1, "swing");
      },
      error: function(xhr, status, error) {
        var err = eval("(" + xhr.responseText + ")");
        alert(err.Message);
      }
    });
  });
});

/* ADDING CATEGORY FORM
--------------------------*/
  
   $(document).on("click", "#submit_form", function(event){
    console.log("form submitted!")  // sanity check
    categ_created();
    });
   
    function categ_created() {
    frm = $("#title_form")
    $.ajax({
       data: frm.serialize(), 
       type: frm.attr('method'), 
       url: frm.attr('action'), 
       async: "false",
       crossOrigin: true,
        // handle a successful response
        success : function(data) {
          if(data.success == true)
          {
          load_categories();
          }
        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
    });
}

/* LOADING CATEGORIES 
------------------------*/

function load_categories(){

$.ajax({
       url: "http://127.0.0.1:8000/encrypter/api/categories/",  
       type: "GET", 
       async: "false",
       crossOrigin: true,
       data: {
        csrfmiddlewaretoken: window.CSRF_TOKEN
    },
       success : function(data) {
         categs = data.results;
         let cats = '';
  
          for(let i=0; i<categs.length ; i++)
          {
           url = "{% url 'encrypter:store' %}?cat="+categs[i].id
           cats += '<div class="card inner-form col-12 col-md-3 col-lg-3 text-center">' +
               '<a name="' + categs[i].id + '" class="rm-icon float-right"><i class="fa fa-trash-o" aria-hidden="true"></i></a>' +
               /*'<div class="card-head cat-title"><h3>' + 
                  categs[i].title +
               '</h3></div>'*/ 
               '<div id="' + categs[i].id + '" class="panopen-text">' + 
               categs[i].title +
                 //'<a href=' + url + '><i id="add_plat" class="fa fa-2x fa-plus-square ic" aria-hidden="true"></i></a>' +
               '</div>' +
              '</div>';
       }
       cats += '<div id="cat_form" class="card inner-form col-12 col-md-3 col-lg-3 text-center">' +
               '<div class="card-body">' + 
                 '<i id="add_cat" class="fa fa-4x fa-plus-square ic" aria-hidden="true"></i>' +
               '</div>' +
              '</div>';

       $("#cats-inner").html(cats)    
       }
}); 


}




/* LOADING PASSWORDS FUNCTION 
--------------------------------*/

function loadpass(cook){
   
   $.ajax({
           url: "http://127.0.0.1:8000/encrypter/api/passwords/?cat=" + cook,
           type: "GET",
           async: "false",
           crossOrigin: true,
           success: function(data) {
            
             data = data.results;
                 let pass = "";
                 console.log(data);
                 let url = "{% url 'encrypter:store' %}?cat=" +  cook;
                  for(let i=0;i<data.length;i++)
                  { 
                    pass += "<div class='input-group col-12 col-md-3 col-lg-3 mb-2'>" + 
                            "<div class='input-group-prepend'>" +
                            "<div class='input-group-text'>" + data[i].icon + "</div>" +
                            "</div>" + 
                            "<input type='text' name='" + data[i].id + "' class='form-control lockit' id='inlineFormInputGroupUsername2' value='" + data[i].password + "' placeholder='Password'>" +
                            "<div class='input-group-append'>" + 
                            "<span class='input-group-text' id='basic-addon2'><i id='" + data[i].category + "' name='" + data[i].id + "' class='pass-cross fa fa-times' aria-hidden='true'></i></span>" + 
                            "</div></div>";
                     
                           //let selector = "#" + categs[j].id;
                           $("#pass-row").html("");      
                          
                       }
                       console.log(url);
                       pass += "<div class='col-12 col-md-3 col-lg-3 mb-2'>" +  
                            "<a href=" + url + " class='add-btn btn btn-primary'>Add Passwords</a>" +
                            "</div>";
                       
                        $("#pass-row").html(pass);  
                        $(".pass-panel").css("display","block");
                        toglockit();
            }
                        });  
  }

/* TOGGLE CATEGORIES
----------------------*/

$(document).on("click","#master-submit",function(){

let id = $(this).attr("name");
let form = $("#mform");
if ($("#master-key").val() !== "")
{
 $.ajax({
       data: form.serialize(), 
       type: form.attr('method'), 
       url: form.attr('action'), 
       async: "false",
       crossOrigin: true,
        // handle a successful response
        success : function(data) {
          if(data.success == true)
          {
          /*$(".lockit").each(function(i,v){
             let id = $(v).attr("name");
             console.log(v);
             console.log(id);
             var input = search(id,data.passwords);
             console.log(input);
             console.log($("input"));
             $("input[name=" + input['id'] + "]").attr("placeholder",input['password']);
            });*/
          checkcook();
          }
        },

});
}
else{
  console.log("fail");
}
});


function search(nameKey, myArray){
  console.log("inside search");
 for (var i=0; i < myArray.length; i++) {
   console.log("loop iterates");
    if (myArray[i].id == nameKey) {
      console.log("find it" + JSON.stringify(myArray[i]));
    return JSON.stringify(myArray[i]);
    }
  }
}

/* TOGGLE PASSWORDS
----------------------*/

$(document).on("click",".panopen-text",function(e){
  let cook = $(this).attr("id")
  loadpass(cook);
});

$(document).on("click",".cross-panel",function(){
  $(".pass-panel").css("display","none");
});

/* TOGGLE LOCKIT
------------------*/
function toglockit(){
$("#lockem").css("display","block");

$("#lockem").click(function() {
  let lockthem = [];
  let flag = 0;
$(".lockit").each(function(i, v) {
  console.log(v);
  if($(v).val() == '')
  {
    $(v).attr('placeholder','Field Empty');
    $(v).addClass('redholder');
    flag = 1;
  }
  else{
  let pass = {id:$(v).attr("name"),value:$(v).val()}
  lockthem.push(pass);
  }
  
     });
     console.log(lockthem);

     if(flag == 0)
     {
     $.ajax({
       url: "{% url 'encrypter:encrypter' %}",
       type: "POST",
       data: {"data":JSON.stringify(lockthem)},
       headers: {"X-CSRFToken": csrftoken },
       success: function(data){
          if(data.success == true)
          {
             $("#lockem").css("display","none");
             $(".pass-panel").css("display","none");
             $.ajax({
               url:"{% url 'encrypter:del' %}",
               type:"POST",
               headers: {"X-CSRFToken": csrftoken },
               success: function(data){
                 if(data.master == 'deleted')
                 {
                 checkcook();
                 }
               }

             });
          }
       }
     });
     }
  });
}

/* DELETE CATEGORY API CALL 
-----------------------------*/

$(document).on("click",".rm-icon",function(){
var post_data = {
  'csrfmiddlewaretoken':"{{ csrf_token }}"
}

let id = $(this).attr("name");

$.ajax({
  
  url: "http://127.0.0.1:8000/encrypter/api/categories/" + id + "/",   
       type: "DELETE", 
       data: post_data,
       headers: { "X_METHODOVERRIDE": "DELETE","X-CSRFToken": csrftoken },
       success : function(data) {

         load_categories();
       }
});
});

/* DELETE PASSWORD API CALL
-----------------------------*/

$(document).on("click",".pass-cross",function(){

let cook = $(this).attr("id")
let id = $(this).attr("name");
var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

$.ajax({
  
  url: "http://127.0.0.1:8000/encrypter/api/passwords/" + id + "/",   
       type: "DELETE", 
       headers: { "X_METHODOVERRIDE": "DELETE","X-CSRFToken": csrftoken },
       success : function() {
         loadpass(cook);
       }
});
});

});
</script>

{% endblock %}

Passman/apps/encrypter/templates/encrypter/index.html
{% extends '_base.html' %}
{% load static %}
{% block title %}PassMan{% endblock %}

{% block header_css %}
<link rel="stylesheet" href="{% static 'encrypter/css/style.css' %}">
{% endblock %}

{% block header_js %}
<script src="{% static 'assets/js/essentials.js' %}"></script>
{% endblock %}

{% block page %}

      <div class="page-main w-100 toggled">
        {% include 'encrypter/components/_sidebar.html' %}
        <div id="content">
            {% include "encrypter/components/_header.html" %}
            <div class="px-2" style="margin-bottom: 80px;">
            {% block content %}

            <!-- Master Password Loader 

            <div class="m-curtains-set">
              <div class="ml-curtain">
              </div>
              <div class="mr-curtain">
              </div>
            </div>

            Master Password Loader Ends -->

            <!-- App Section -->

            <div class="container text-center password-box">
            {% block categories %}
            
            {% endblock %}
            </div>

            <!-- App Section Ends -->

            {% endblock %}
            </div>
            {% include "encrypter/components/_footer.html" %}
        </div>        
      </div>

{% endblock %}

{% block footer_js %}

<script src="{% static 'encrypter/js/main.js' %}"></script>

{% endblock %}

Passman/apps/encrypter/templates/encrypter/store.html
{% extends '_base.html' %}
{% load static %}

{% block header_css %}
<link rel="stylesheet" href="{% static 'encrypter/css/style.css' %}">
{% endblock %}

{% block header_js %}
<script src="{% static 'assets/js/essentials.js' %}"></script>
<script src="{% static 'encrypter/js/platter.js' %}"></script>

{% endblock %}

{% block page %}
    
      <div class="page-main w-100 toggled">
        {% include 'encrypter/components/_sidebar.html' %}
        <div id="content">
   
            {% include "encrypter/components/_header.html" %}
            <div class="px-2" style="margin-bottom: 80px;">

            <!--Loader--> 
        <div class="lds-facebook"><div></div><div></div><div></div></div>

            {% block content %}
        
        
            <div class="input-group offset-2 col-8">
              <input id="search" type="search" class="form-control" placeholder="I'm Searching for..">
              <span><i class="fa fa-2x fa-arrow-circle-right" aria-hidden="true"></i></span>
            </div>
          
           <div class="plat-section">
            <div class="row platrow">
        
            </div>
           </div>
            {% endblock %}
            </div>
            {% include "encrypter/components/_footer.html" %}
        </div>        
      </div>
{% endblock %}

{% block footer_js %}
<script src="{% static 'encrypter/js/store.js' %}"></script>

<script>
var url_string = window.location.href;
var url = new URL(url_string);
var c = url.searchParams.get("cat");
setCookie("user","{{user.id}}");
setCookie("cat",c);



</script>
{% endblock %}